version: '3.8'
volumes:
  postgres_data:
services:
  booking-postgres:
    image: daxnet/booking-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking
    volumes:
      - postgres_data:/data:Z
    ports:
      - "5432:5432"
  booking-auth-service:
    image: daxnet/booking-auth-service
    environment:
      - ConnectionStrings__DefaultConnection=Host=booking-postgres;Database=booking_aspnet_identity;Username=postgres;Password=postgres
      - identityServer__issuer=http://booking-auth-service:9001
    links:
      - booking-postgres
    ports:
      - 9001:9001
  booking-meetingrooms-service:
    image: daxnet/booking-meetingrooms-service
    environment:
      - db__connectionString=Host=booking-postgres;Database=booking;Username=postgres;Password=postgres
      - authority__url=http://booking-auth-service:9001
      - Logging__LogLevel__Default=Debug
    links:
      - booking-postgres
      - booking-auth-service
    ports:
      - 9002:9002