version: '3.8'
services:
    booking-postgres:
        image: daxnet/booking-postgres
        build:
            context: docker/postgres
            dockerfile: Dockerfile
    booking-meetingrooms-service:
        image: daxnet/booking-meetingrooms-service
        build: 
            context: src
            dockerfile: Booking.Services.MeetingRooms/Dockerfile
    # booking-reservation-service:
    #     image: daxnet/booking-reservation-service
    #     build:
    #         context: src
    #         dockerfile: Booking.Services.Reservations/Dockerfile
    booking-auth-service:
        image: daxnet/booking-auth-service
        build:
            context: src
            dockerfile: Booking.Services.Auth/Dockerfile
    booking-nginx:
        image: daxnet/booking-nginx
        build:
            context: docker/nginx
            dockerfile: Dockerfile
    booking-web:
        image: daxnet/booking-web
        build:
            context: src
            dockerfile: Booking.WebApp/Dockerfile